/// <reference types = "cypress" />


// describe('Test case 10 times', function () {
//     it('Try it 10 times', function () {
//         var i = 0;
//         for (i = 0; i < 10; i++) {


describe('mobile-tests', () => {

    const clearTrys = () => {
        cy.window().then((win) => {
            if (win.resetDailyLimit) {
                return new Cypress.Promise((resolve) => {
                    win.resetDailyLimit().then(() => {
                        resolve();
                    })
                });
            }
        });
    }


    before(() => {
        cy.clearLocalStorage();


    })
    beforeEach(() => {
        cy.viewport(375, 812)
        cy.viewport('iphone-x')
        cy.on('uncaught:exception', (err, runnable) => {
            return false;
        });
    })
    context('Asserti', () => {
        beforeEach(() => {
            cy.restoreLocalStorage();

        });

        afterEach(() => {
            cy.saveLocalStorage();
        });

        // if (i === 0) {
        //LOGIN
        it('Login', () => {


            cy.visit('http://localhost:3000/')




            cy.get('[class="inputHomePage"]')
                .click()
                .type('20694dc4-caf6-4613-83d2-fe95ebbfe3cf')
            cy.wait(1000)
            const button = cy.get('[class="HP_Button"]')
            button.click()
            // button.click()

            cy.wait(2000)
        })
        // }
        //DAS QUIZ v.1
        it('Quiz #1', () => {

            clearTrys();

            cy.get('[alt="Next button of DAS QUIZ"]').click()
            cy.get('.quizKatText')
                .should('contain', 'Kategorien')

            cy.get('ul>li').eq(0).click()
            cy.get('.quizCountQuestion')
                .should('contain', '1')
            cy.get('ul>li').eq(1)
                .should('contain', 'B')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '2')
            cy.get('ul>li').eq(2)
                .should('contain', 'C')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '3')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '4')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '5')
            cy.get('ul>li').eq(0)
                .should('contain', 'A')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '6')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '7')
            cy.get('ul>li').eq(1)
                .should('contain', 'B')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '8')
            cy.get('ul>li').eq(0)
                .should('contain', 'A')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '9')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', 'AUSWERTUNG')

            //Answers
            cy.get('[alt="Arrow"]')
                .click()
            cy.get('[alt="Arrow"]')
                .eq(1)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(3)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(5)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(6)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(0)
                .click()
            cy.get('.menuDiv').eq(1)
                .click()

            cy.get('.singleQuizCategoriesItem').eq(0)
                .should('contain', 'Dein bisher bester Versuch: ')


            cy.get('.menuDiv').eq(0)
                .click()

        })

        //DAS QUIZ v.2
        it('Quiz #2', () => {


            cy.wait(2000)
            cy.get('[alt="Next button of DAS QUIZ"]').click()
            cy.get('.quizKatText')
                .should('contain', 'Kategorien')

            cy.get('ul>li').eq(3).click()
            cy.get('.quizCountQuestion')
                .should('contain', '1')
            cy.get('ul>li').eq(1)
                .should('contain', 'B')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '2')
            cy.get('ul>li').eq(2)
                .should('contain', 'C')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '3')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '4')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '5')
            cy.get('ul>li').eq(0)
                .should('contain', 'A')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '6')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '7')
            cy.get('ul>li').eq(1)
                .should('contain', 'B')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '8')
            cy.get('ul>li').eq(0)
                .should('contain', 'A')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', '9')
            cy.get('ul>li').eq(3)
                .should('contain', 'D')
                .click()
            cy.get('a>button').click()

            cy.get('.quizCountQuestion')
                .should('contain', 'AUSWERTUNG')

            //Answers
            cy.get('[alt="Arrow"]')
                .click()
            cy.get('[alt="Arrow"]')
                .eq(1)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(3)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(5)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(6)
                .click()
            cy.get('[alt="Arrow"]')
                .eq(0)
                .click()

            cy.get('.menuDiv').eq(1)
                .click()

            cy.get('.singleQuizCategoriesItem').eq(0)
                .should('contain', 'Dein bisher bester Versuch: ')
            cy.get('button')
                .click()

        })

        //RANKING
        it('Ranking', () => {
            cy.get('.menuDiv')
                .eq(3)
                .click()
                .wait(2000)
            cy.get('.containerImg>div>div')
                .should('contain', 'CREDITS')
            cy.get('.bigText')
                .should('contain', 'DU BIST GERADE')
                .wait(500)
            cy.get('.menuDiv')
                .eq(0)
                .click()
        })

        //DAS QUIZ after 2 times
        it('Quiz fail try', () => {
            cy.get('[alt="Next button of DAS QUIZ"]').click()

            cy.get('.singleQuizQuestionItem>div')
                .should('contain', 'WOW, DU STARTEST JA RICHTIG DURCH!')
                .wait(500)
                .find('button')
                .click()
        })


        //DAS WISSENSMODUL
        it('Wissenmodul', () => {
            cy.get('.menuDiv')
                .eq(2)
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('.upperItemFact')
                .should('contain', 'Nr.')
            cy.get('[alt="Fact"]')
                .eq(1)
                .click()

            cy.get('ul>li')
                .eq(1)
                .click()
            cy.get('ul>li')
                .eq(0)
                .should('contain', 'Fakt')
            cy.get('ul>li')
                .eq(1)
                .should('contain', 'Fakt')
            cy.get('[alt="Close Button"]')
                .click()

            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('ul>li')
                .eq(0)
                .should('contain', 'Fakt')
            cy.get('ul>li')
                .eq(1)
                .should('contain', 'Fakt')
            cy.get('[alt="Close Button"]')
                .click()

            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('ul>li')
                .eq(0)
                .should('contain', 'Fakt')
            cy.get('ul>li')
                .eq(1)
                .should('contain', 'Fakt')
            cy.get('[alt="Close Button"]')
                .click()

            cy.get('ul>li')
                .eq(4)
                .click()
            cy.get('ul>li')
                .eq(0)
                .should('contain', 'Fakt')
            cy.get('ul>li')
                .eq(1)
                .should('contain', 'Fakt')
            cy.get('[alt="Close Button"]')
                .click()

            cy.get('ul>li')
                .eq(5)
                .click()
            cy.get('ul>li')
                .eq(0)
                .should('contain', 'Fakt')
            cy.get('ul>li')
                .eq(1)
                .should('contain', 'Fakt')
            cy.get('[alt="Close Button"]')
                .click()

            cy.get('ul>li')
                .eq(6)
                .click()
            cy.get('ul>li')
                .eq(0)
                .should('contain', 'Fakt')
            cy.get('ul>li')
                .eq(1)
                .should('contain', 'Fakt')
            cy.get('[alt="Close Button"]')
                .click()
            cy.get('.menuDiv')
                .eq(0)
                .click()

        })

        //HASHTAG & LINKS
        it('Hashtag & Links', () => {
            cy.get('.menuDiv')
                .eq(2)
                .click()

            //1 Kategorie
            cy.get('ul>li')
                .eq(1)
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(4)
                .click()
            cy.get('span>a')
                .eq(3)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()

            //2 Kategorie
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(3)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('span>a')
                .eq(3)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()

            // 3 Kategorie
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('ul>li')
                .eq(1)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(3)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()

            // 4 Kategorie
            cy.get('ul>li')
                .eq(4)
                .click()
            cy.get('ul>li')
                .eq(1)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(3)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()

            // 5 Kategorie
            cy.get('ul>li')
                .eq(5)
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(1)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()


            // 6 Kategorie
            cy.get('ul>li')
                .eq(6)
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()



            // 7 Kategorie
            cy.get('ul>li')
                .eq(6)
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .should('contain', '#')
            cy.get('span>a')
                .should('contain', 'https://')
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(3)
                .click()
            cy.get('span>a')
                .eq(1)
                .should('contain', '#')
                .click()
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('span>a')
                .eq(0)
                .should('contain', '#')
                .click()
            cy.get('.menuDiv')
                .eq(2)
                .click()
            cy.get('.menuDiv')
                .eq(0)
                .click()


        })

        //AUSWERTUNG
        it.skip('Auswertung', () => {
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('ul>li')
                .eq(0)
                .click()

            cy.get('.singleQuizQuestionItem')
                .eq(0)
                .should('contain', 'Wann hast du am STARTKLAR Aktionstag teilgenommen?')
            cy.get('.react-datepicker__input-container>input')
                .click({ force: true })
            cy.get('[aria-label="Choose Montag, 6. September 2021"]')
                .click()

            cy.get('.singleQuizQuestionItem')
                .eq(1)
                .should('contain', 'Wie alt bist du?')
            cy.get('div>select')
                .select('18')

            cy.get('.singleQuizQuestionItem')
                .eq(2)
                .should('contain', 'Welches Geschlecht hast du?')
            cy.get('[value="M"]')
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(3)
                .should('contain', 'Wie hat dir der STARTKLAR Aktionstag ganz allgemein gefallen?')
                .find('button>div')
                .eq(4)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(4)
                .should('contain', 'Wie hat dir die Organisation des STARTKLAR Aktionstages gefallen?')
                .find('button>div')
                .eq(3)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(5)
                .should('contain', 'Wie fandest du deine Moderator?')
                .find('button>div')
                .eq(4)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(6)
                .should('contain', 'Hast du dir im Vorfeld des Aktionstages die STARTKLAR APP heruntergeladen?')
            cy.get('[value="Ja"]')
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(7)
                .should('contain', 'Wie häufig hast du die App genutzt?')
            cy.get('[value="Mehrmals in der Woche"]')
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(8)
                .should('contain', 'Welcher Bereich der STARTKLAR App hat dir am besten gefallen?')
            cy.get('[value="Quiz"]')
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(9)
                .should('contain', 'Wie wahrscheinlich ist es, dass du die STARTKLAR App auch in Zukunft weiter nutzen wirst?')
                .find('button>div')
                .eq(5)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(10)
                .should('contain', 'Wie hat dir das Startklar Brettspiel gefallen?')
                .find('button>div')
                .eq(3)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(11)
                .should('contain', 'Würdest du das Spiel zu einem anderen Zeitpunkt nochmal spielen wollen?')
                .find('button>div')
                .eq(5)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(12)
                .should('contain', 'Hast du durch das STARTKLAR Brettspiel etwas gelernt?')
                .find('div>textarea')
                .type('Ja')

            cy.get('.singleQuizQuestionItem')
                .eq(13)
                .should('contain', 'Wie hat dir das STARTKLAR VR-Modul gefallen?')
                .find('button>div')
                .eq(5)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(14)
                .should('contain', 'Hast du durch das STARTKLAR VR-Modul etwas gelernt?')
                .find('div>textarea')
                .type('Ja')

            cy.get('.singleQuizQuestionItem')
                .eq(15)
                .should('contain', 'Wie hat dir das STARTKLAR Modul KnowHow gefallen?')
                .find('button>div')
                .eq(5)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(16)
                .should('contain', 'Hast du durch das STARTKLAR Modul KnowHow etwas gelernt?')
                .find('div>textarea')
                .type('Ja')

            cy.get('.singleQuizQuestionItem')
                .eq(17)
                .should('contain', 'Wie hat dir das STARTKLAR Modul „Alles Klar?“ gefallen?')
                .find('button>div')
                .eq(2)
                .click({ force: true })

            cy.get('.singleQuizQuestionItem')
                .eq(18)
                .should('contain', 'Hast du durch das STARTKLAR Modul „Alles klar?“ etwas gelernt?')
                .find('div>textarea')
                .type('Ja')

            cy.get('.singleQuizQuestionItem')
                .eq(19)
                .should('contain', 'Würdest du das Modul „Alles Klar?“ gerne weiter im Unterricht behandeln?')
                .find('div>textarea')
                .type('Nein')

            cy.get('.singleQuizQuestionItem')
                .eq(20)
                .should('contain', 'Gibt es etwas, was wir verbessern müssen?')
                .find('div>textarea')
                .type('Nein')


            cy.get('.singleQuizQuestionItem')
                .eq(21)
                .should('contain', 'Gibt es etwas, was du uns mitteilen möchtest?')
                .find('div>textarea')
                .type('Nein')

            cy.get('.singleQuizQuestionItem')
                .eq(22)
                .should('contain', 'Bewertest du deinen eigenen Alkoholkonsum nach dem heutigen Tag anders?')
                .find('div>textarea')
                .type('Nein')

            cy.get('ul>div>button')
                .eq(1)
                .click({ force: true })
                .wait(500)

            //Error when you don't press all red containers
            cy.get('.singleQuizQuestionItem')
                .eq(24)
                .should('contain', 'Bitte fülle alle Felder mit rotem Rand aus Oder verwenden Sie nur erlaubte Zeichen')
                .wait(500)
                .click()

            cy.get('.singleQuizQuestionItem')
                .eq(23)
                .should('contain', 'Glaubst du, dass du in Zukunft verantwortungsbewusster mit Alkohol umgehen wirst?')
                .find('button>div')
                .eq(3)
                .click({ force: true })

            cy.get('ul>div>button')
                .eq(1)
                .click({ force: true })

            cy.get('.bigText')
                .should('contain', 'EVALUATION ERFOLGREICH BEENDET')
            cy.get('.smallText')
                .should('contain', 'Viele Dank für dein Feedback')

            cy.get('div>button')
                .click()

        })

        //AKTIONSTAG
        it('Aktionstag', () => {
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.get('ul>li')
                .eq(1)
                .click()
            cy.get('div>span')
                .eq(0)
                .should('contain', 'TAGESABLAUF')
            cy.get('div>span')
                .eq(2)
                .should('contain', 'ZIELE')
            cy.get('div>button')
                .click()
        })

        //EINDRUCKE
        it('Eindrucke', () => {
            cy.get('ul>li')
                .eq(2)
                .click()
            cy.wait(2000)
            cy.get('[alt="/static/media/1.3494c843.jpg"]')
                .click()
            cy.wait(1000)
            cy.get('div>button')
                .eq(1)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
            cy.get('div>button')
                .eq(2)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
                .click()
                .wait(500)
            cy.get('ul>li>button')
                .eq(0)
                .click()
                .wait(1000)
            cy.get('ul>li>button')
                .eq(0)
                .click()
                .wait(1000)
            cy.get('ul>li>button')
                .eq(0)
                .click()
                .wait(1000)
            cy.get('ul>li>button')
                .eq(1)
                .click()
                .wait(500)
            cy.get('ul>li>button')
                .eq(1)
                .click()
                .wait(500)
            cy.get('ul>li>button')
                .eq(1)
                .click()
                .wait(500)
            cy.get('ul>li>button')
                .eq(2)
                .click()
                .wait(1000)
            cy.get('div>button')
                .click()
            cy.get('.quizKatText')
                .should('contain', 'Kategorien')
            cy.get('.menuFotter>a')
                .eq(0)
                .click()

        })

        //FAKT DES TAGES
        it('Fakt', () => {
            cy.get('.faktOfTheDayGradient')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowRight')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowRight')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowLeft')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowLeft')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowLeft')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowLeft')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowRight')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('.factArrowRight')
                .click()
                .wait(500)
            cy.get('.upperItemFact>span')
                .should('contain', 'Nr.')
            cy.get('[alt="Logo"]')
                .click()
                .wait(500)
            cy.get('.upperItemMenuContent')
                .eq(0)
                .should('contain', 'DAS QUIZ')

        })


        //ERSTE HILFE
        it('Erste', () => {
            cy.get('.upperItemMenuContent')
                .should('contain', 'ERSTE HILFE')
                .eq(3)
                .click()


            //TOP BAR
            cy.get('.faktOfTheDayGradient>span')
                .should('contain', 'NOTFALL? - 112 ANRUFEN')

            cy.get('.faktOfTheDayGradient>span>span')
                .should('contain', 'Bereite dich auf folgende Fragen vor:')

            cy.get('.faktOfTheDayGradient>span')
                .should('contain', 'Wo? Was? Wie viele? Welche Verletzungen? Warten')





            cy.get('.itemName')
                .eq(0)
                .should('contain', 'ANZEICHEN FÜR SUCHT')
                .click()
            cy.get('.quizContainer>div>div>span')
                .should('contain', 'WIE ERKENNE ICH, OB ICH ODER EIN FREUND / EINE FREUNDIN EIN SUCHTVERHALTEN AUFWEIST?')
            cy.get('.quizContainer>div>div>button')
                .should('contain', 'ZU DEN KATEGORIEN')
                .click()

            cy.get('.itemName')
                .eq(1)
                .should('contain', 'ÜBERPRÜFE DICH SELBST')
                .click()
            cy.get('.quizContainer>div>div>span')
                .should('contain', 'ALKOHOLTESTS UND PROGRAMM ZUR REDUZIERUNG DES ALKOHOLKONSUMS')
            cy.get('.upperItemMenuContent>span')
                .eq(0)
                .should('contain', 'IST ALKOHOL EIN PROBLEM FÜR DICH?')
                .click()

            //CHECK YOURSELF (No problem)
            cy.get('.quizContainer>div>div>div>span')
                .should('contain', 'IST ALKOHOL EIN PROBLEM FÜR DICH?')


            cy.get('.singleQuizCategoriesItem')
                .eq(0)
                .should('contain', 'Halten Sie pro Woche mindestens zwei alkoholfreie Tage ein?')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(1)
                .should('contain', 'Wenn Sie Alkohol trinken, trinken Sie typischerweise mehr als ein (gilt für Frauen) bzw.')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(2)
                .should('contain', 'Haben Sie in den vergangenen 30 Tagen zu einer Gelegenheit vier (gilt für Frauen) bzw.')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(3)
                .should('contain', 'Haben Sie in den letzten 12 Monaten erlebt, dass Sie nicht mehr mit dem Trinken')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(4)
                .should('contain', 'Ist es in den letzten 12 Monaten passiert, dass Sie wegen des Trinkens Erwartungen,')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(5)
                .should('contain', 'Kam es in den letzten 12 Monaten vor, dass Sie am Morgen ein alkoholisches Getränk brauchten')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(6)
                .should('contain', 'Hatten Sie während der letzten 12 Monate wegen Ihrer Trinkgewohnheiten Schuldgefühle oder')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(7)
                .should('contain', 'Kam es während der letzten 12 Monate vor, dass Sie sich nicht mehr an den')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(8)
                .should('contain', 'Hat in den letzten 12 Monaten jemand aus Ihrem Verwandten- oder Freundeskreis')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(9)
                .should('contain', 'Haben Sie während der letzten 12 Monate sich oder eine andere Person unter Alkoholeinfluss')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })


            cy.get('ul>div>button')
                .eq(1)
                .should('contain', 'WEITER')
                .click()

            cy.get('.quizContainer>div>div>div>div>span')
                .should('contain', 'IST ALKOHOL EIN PROBLEM FÜR DICH?')
            cy.get('.quizContainer>div>div>div')
                .should('contain', 'It seems that your are all good')

            cy.get('.quizContainer>div>div>div>button')
                .should('contain', 'ZURÜCK')
                .click()




            //CHECK YOURSELF (With problem)
            cy.get('.upperItemMenuContent>span')
                .should('contain', 'IST ALKOHOL EIN PROBLEM FÜR DICH?')
                .eq(0)
                .click()


            cy.get('.singleQuizCategoriesItem')
                .eq(0)
                .should('contain', 'Halten Sie pro Woche mindestens zwei alkoholfreie Tage ein?')
                .find('div>button')
                .eq(0)
                .should('contain', 'JA')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(1)
                .should('contain', 'Wenn Sie Alkohol trinken, trinken Sie typischerweise mehr als ein (gilt für Frauen) bzw.')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(2)
                .should('contain', 'Haben Sie in den vergangenen 30 Tagen zu einer Gelegenheit vier (gilt für Frauen) bzw.')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(3)
                .should('contain', 'Haben Sie in den letzten 12 Monaten erlebt, dass Sie nicht mehr mit dem Trinken')
                .find('div>button')
                .eq(0)
                .should('contain', 'JA')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(4)
                .should('contain', 'Ist es in den letzten 12 Monaten passiert, dass Sie wegen des Trinkens Erwartungen,')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(5)
                .should('contain', 'Kam es in den letzten 12 Monaten vor, dass Sie am Morgen ein alkoholisches Getränk brauchten')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(6)
                .should('contain', 'Hatten Sie während der letzten 12 Monate wegen Ihrer Trinkgewohnheiten Schuldgefühle oder')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(7)
                .should('contain', 'Kam es während der letzten 12 Monate vor, dass Sie sich nicht mehr an den')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(8)
                .should('contain', 'Hat in den letzten 12 Monaten jemand aus Ihrem Verwandten- oder Freundeskreis')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })

            cy.get('.singleQuizCategoriesItem')
                .eq(9)
                .should('contain', 'Haben Sie während der letzten 12 Monate sich oder eine andere Person unter Alkoholeinfluss')
                .find('div>button')
                .eq(1)
                .should('contain', 'NICHT')
                .click({ force: true })


            cy.get('ul>div>button')
                .eq(1)
                .should('contain', 'WEITER')
                .click()

            cy.get('.quizContainer>div>div>div>div>span')
                .should('contain', 'IST ALKOHOL EIN PROBLEM FÜR DICH?')
            cy.get('.quizContainer>div>div>div')
                .should('contain', 'You have problem')

            cy.get('.quizContainer>div>div>div>button')
                .should('contain', 'ZURÜCK')
                .click()

        })

        //CHECK YOUR DRINKING/CHANGE YOUR DRINKING AFTER CHECK YOURSELF
        it('Check', () => {
            cy.get('.singleQuizCategoriesItem')
                .eq(1)
                .should('contain', 'CHECK YOUR DRINKING')
                .find('.nextPageButton')
                .should('have.attr', 'src')


            cy.get('.singleQuizCategoriesItem')
                .eq(2)
                .should('contain', 'CHANGE YOUR DRINKING')
                .find('.nextPageButton')
                .should('have.attr', 'src')

            cy.get('.quizContainer>div>div>button')
                .should('contain', 'ZU DEN KATEGORIEN')
                .click()
        })

        //KONTAKT
        it('Kontakt', () => {
            cy.get('.itemName')
                .eq(3)
                .should('contain', 'KONTAKT')
                .click()

            cy.get('.quizContainer>div>div>span')
                .should('contain', 'SPRICH MIT JEMANDEM DRÜBER')

            cy.get('.singleQuizCategoriesItem')
                .eq(0)
                .find('span')
                .should('contain', 'Du kannst mit Freunden oder deiner Familie reden und dir - auch anonym - Infos und Hilfe holen beim')
            cy.get('.singleQuizCategoriesItem>span>a')
                .should('contain', 'http://www.bzga.de/service/beratungsstellen/suchtprobleme/')
            cy.get('.singleQuizCategoriesItem>span')
                .find('a')
                .should('have.attr', 'href')

            cy.get('div>button')
                .should('contain', 'ZU DEN KATEGORIEN')
                .click()

            cy.get('.menuDiv')
                .eq(0)
                .click()
        })


    })
})


//         }
//     })
// })




